version: '3'
services:
  proxy:
    container_name: proxy
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
    sysctls:
      net.core.somaxconn: 8192
      net.ipv4.ip_local_port_range: "1024 65535"
  app1:
    image: golang:1.16
    container_name: "app1"
    volumes:
      - ./backend_1:/go/src/app
    working_dir: /go/src/app
    environment:
      - Asia/Tokyo
    tty: true
    ports:
      - 8080:8080
    sysctls:
      net.core.somaxconn: 8192
      net.ipv4.ip_local_port_range: "1024 65535"
    command: /bin/bash -c "go run main.go"
  app2:
    image: golang:1.16
    container_name: "app2"
    volumes:
      - ./backend_2:/go/src/app
    working_dir: /go/src/app
    environment:
      - Asia/Tokyo
    tty: true
    ports:
      - 8081:8081
    sysctls:
      net.core.somaxconn: 8192
      net.ipv4.ip_local_port_range: "1024 65535"
    command: /bin/bash -c "go run main.go"
