version: '3'
services:
  golang:
    image: golang:1.16
    container_name: 'golang'
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ".:/go/src/app"
    working_dir: /go/src/app
    ports:
      - 5000:5000
